name: wordpress
version: 1.0.0
appVersion: 1.0.0
description: Web publishing platform for building state websites.
icon: https://auth.s3waas.gov.in/sites/default/files/logo.png
keywords:
- wordpress
- cms
- blog
- http
- web
- application
- php
home: https://s3waas.gov.in/
sources:
- https://github.com/bitnami/bitnami-docker-wordpress
maintainers:
- name: Priyaranjan Jena
  email: priyaranjan.653@gmail.com
engine: gotpl
