apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.applicationAdminPassword }}
  application-admin-password: {{ default "" .Values.applicationAdminPassword | b64enc | quote }}
  {{ else }}
  application-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  # smtp-password: {{ default "" .Values.smtpPassword | b64enc | quote }}

  object-storage-key: {{ default "" .Values.S3waasObjectStorageKey | b64enc | quote }}
  object-storage-secret: {{ default "" .Values.S3waasObjectStorageSecret | b64enc | quote }}